Select top 10 SALESID,SALESNAME,TRANSFERWHAREHOUSE,ATHSALESTYPE,
NUMBERSEQUENCEGROUP,SALESSTATUS,SALESTYPE,ATHDNSTATUS,INVOICEACCOUNT,
CURRENCYCODE,PURCHORDERFORMNUM,CUSTOMERREF,CUSTACCOUNT,TAXGROUP,SHIPPINGDATEREQUESTED,
SHIPPINGDATECONFIRMED,CREATEDDATETIME
 from salestable where CREATEDDATETIME > '2020-01-01'


Select top 100 st.SALESID,sl.ITEMID,inv.ITEMNAME,sl.SALESQTY,
idm.INVENTLOCATIONID,idm.INVENTSITEID,sl.SALESUNIT,sl.SALESPRICE,sl.FREEOFCHARGE,
sl.LINEDISC,sl.LINEPERCENT,sl.LINEAMOUNT,sl.TAXITEMGROUP,sl.ATHITEMGROUPIDA,sl.ATHITEMGROUPIDB,sl.ATHITEMGROUPIDC,
 sl.ATHNONFULFILLMENTREASONID
 from salestable as st inner join SALESLINE sl on st.SALESID=sl.SALESID
 inner join INVENTTABLE inv on inv.ITEMID=sl.ITEMID
 left join INVENTDIM idm on idm.INVENTDIMID=sl.INVENTDIMID
  where ST.CREATEDDATETIME > '2026-03-03' 


Select SALESID,ITEMID,ITEMNAME,SALESQTY,
INVENTLOCATIONID,INVENTSITEID,SALESUNIT,SALESPRICE,FREEOFCHARGE,
LINEDISC,LINEPERCENT,LINEAMOUNT,TAXITEMGROUP,ATHITEMGROUPIDA,ATHITEMGROUPIDB,ATHITEMGROUPIDC,
 ATHNONFULFILLMENTREASONID
 from salestable_salesdetail
   
